[2020-04-28 18:27:10,738] {alignmentservice.py:242} MainThread INFO in alignmentservice: Consumer running.......
[2020-04-28 18:28:37,761] {alignmentservice.py:243} MainThread INFO in alignmentservice: Consumer running.......
[2020-04-28 18:35:00,032] {alignmentservice.py:252} MainThread INFO in alignmentservice: Consumer running.......
[2020-04-28 18:45:51,961] {consumer.py:252} MainThread INFO in consumer: Consumer running.......
[2020-04-28 19:14:59,527] {consumer.py:33} MainThread INFO in consumer: Consumer running.......
[2020-05-08 13:42:25,392] {consumer.py:35} MainThread INFO in consumer: Consumer running.......
[2020-05-08 13:52:36,359] {consumer.py:39} MainThread INFO in consumer: Consuming from the Kafka Queue......
[2020-05-08 13:54:41,090] {alignmentservice.py:50} MainThread INFO in alignmentservice: Alignment process starts for job: 15889250265440123
[2020-05-08 13:54:41,101] {consumer.py:44} MainThread ERROR in consumer: Exception while consuming: can only concatenate str (not "dict") to str
[2020-05-08 13:54:41,121] {consumer.py:45} MainThread ERROR in consumer: None
[2020-06-18 12:33:40,850] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
[2020-06-24 14:55:10,979] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 14:57:09,083] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 14:57:49,924] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 14:59:01,687] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:00:13,954] {app.py:29} MainThread INFO in app: Starting
[2020-06-24 15:00:13,955] {alignmentconsumer.py:40} AlignerKafka-Thread INFO in alignmentconsumer: Consumer
[2020-06-24 15:00:14,807] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:02:29,647] {app.py:29} MainThread INFO in app: Starting
[2020-06-24 15:02:30,511] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:03:25,030] {app.py:29} MainThread INFO in app: Starting
[2020-06-24 15:03:25,035] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-06-24 15:03:25,883] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:04:38,075] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:04:55,103] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-06-24 15:05:33,022] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:05:56,558] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-07-01 13:08:59,444] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-07-01 13:09:00,461] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-03 17:43:22,555] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
[2020-07-07 18:10:35,050] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-07 19:22:45,915] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:14:17,627] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:43:58,379] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:44:13,523] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:53:00,436] {sentenceconsumer.py:43} SentenceKafka-Thread INFO in sentenceconsumer: Consumer running.......
[2020-07-08 17:53:00,441] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:53:19,456] {_internal.py:122} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:53:19] "[33mGET / HTTP/1.1[0m" 404 -
[2020-07-08 17:53:20,110] {_internal.py:122} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:53:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2020-07-08 17:53:30,232] {_internal.py:122} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:53:30] "[33mGET / HTTP/1.1[0m" 404 -
[2020-07-08 17:54:54,699] {app.py:1891} Thread-4 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 17:54:54,722] {_internal.py:122} Thread-4 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:54:54] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 18:45:02,404] {sentenceconsumer.py:43} SentenceKafka-Thread INFO in sentenceconsumer: Consumer running.......
[2020-07-08 18:45:02,411] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 18:49:13,657] {sentenceconsumer.py:43} SentenceKafka-Thread INFO in sentenceconsumer: Consumer running.......
[2020-07-08 18:49:13,663] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 18:49:55,533] {app.py:1891} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 18:49:55,565] {_internal.py:122} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 18:49:55] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 18:52:23,826] {app.py:1891} Thread-2 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 18:52:23,828] {_internal.py:122} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 18:52:23] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 18:55:03,004] {app.py:1891} Thread-3 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 18:55:03,007] {_internal.py:122} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 18:55:03] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 18:55:39,355] {app.py:1891} Thread-4 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 18:55:39,358] {_internal.py:122} Thread-4 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 18:55:39] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 18:58:17,979] {sentenceconsumer.py:43} SentenceKafka-Thread INFO in sentenceconsumer: Consumer running.......
[2020-07-08 18:58:17,988] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 18:58:55,320] {app.py:1891} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 18:58:55,335] {_internal.py:122} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 18:58:55] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:00:33,747] {app.py:1891} Thread-2 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:00:33,751] {_internal.py:122} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:00:33] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:00:52,992] {app.py:1891} Thread-3 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:00:52,995] {_internal.py:122} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:00:52] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:01:26,152] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 19:02:03,480] {app.py:1891} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:02:03,486] {_internal.py:122} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:02:03] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:05:08,829] {app.py:1891} Thread-2 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:05:08,836] {_internal.py:122} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:05:08] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:05:22,058] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 19:05:56,157] {app.py:1891} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:05:56,163] {_internal.py:122} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:05:56] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:08:12,811] {app.py:1891} Thread-2 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/restful/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:08:12,813] {_internal.py:122} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:08:12] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 19:25:02,320] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 19:25:41,046] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 19:25:41,053] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 19:25:41] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:25:06,961] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 21:25:42,341] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:25:42,347] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:25:42] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:26:43,873] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:26:43] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2020-07-08 21:29:41,197] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 21:31:16,997] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:31:17,001] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:31:17] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:36:40,523] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 21:37:31,423] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:37:31,430] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:37:31] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:38:11,179] {app.py:1892} Thread-2 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:38:11,181] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:38:11] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:39:21,170] {app.py:1892} Thread-3 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:39:21,172] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:39:21] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:40:06,437] {app.py:1892} Thread-4 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:40:06,438] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:40:06] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:47:13,124] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 21:48:12,860] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:48:12,871] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:48:12] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:58:14,238] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 21:58:33,923] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:58:33] "[33mGET / HTTP/1.1[0m" 404 -
[2020-07-08 21:58:48,023] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:58:48] "[33mGET / HTTP/1.1[0m" 404 -
[2020-07-08 21:58:51,725] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:58:51,734] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:58:51] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 21:59:41,949] {app.py:1892} Thread-4 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 24, in createalignmentjob
    return service.register_job(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 42, in register_job
    self.update_job_details(response, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 21:59:41,958] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 21:59:41] "[35m[1mPOST //anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 22:00:23,732] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 22:00:23,732] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:00:24,338] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:00:24,676] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:01:13,996] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 22:01:13] "[35m[1mPOST //anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 22:01:56,823] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 22:01:56] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 22:05:32,247] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/app.py', reloading
[2020-07-08 22:05:32,718] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:05:33,450] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:05:33,451] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:06:26,405] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/app.py', reloading
[2020-07-08 22:06:26,541] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:06:27,323] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:06:27,323] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:07:05,973] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 22:07:05] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-08 22:16:22,543] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py', reloading
[2020-07-08 22:16:22,818] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:16:23,544] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:16:23,545] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:16:33,825] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 22:16:33,826] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:16:34,479] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:16:34,480] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:18:30,411] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py', reloading
[2020-07-08 22:18:30,643] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:18:31,542] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:18:31,542] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:19:54,217] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-08 22:19:54,385] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:19:55,373] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:19:55,373] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:20:59,290] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-08 22:20:59,455] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:21:00,481] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:21:00,482] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:21:03,566] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 22:21:03,567] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:21:04,169] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:21:04,170] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:24:04,540] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 22:24:04] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines_status HTTP/1.1[0m" 500 -
[2020-07-08 22:28:29,024] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 22:28:29,025] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-08 22:28:29,649] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-08 22:28:29,649] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 209-032-784
[2020-07-08 22:29:05,788] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 22:29:05] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines_status HTTP/1.1[0m" 500 -
[2020-07-08 22:29:35,709] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 22:29:35] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 07:53:26,059] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 07:53:26,060] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 07:53:26,706] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 07:53:27,040] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 07:54:49,857] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 07:54:49] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-09 07:58:38,704] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py', reloading
[2020-07-09 07:58:38,831] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 07:58:39,552] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 07:58:39,552] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 07:59:20,337] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 07:59:20] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 08:14:49,552] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py', reloading
[2020-07-09 08:14:49,734] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 08:14:50,531] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 08:14:50,532] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 08:15:12,216] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/app.py', reloading
[2020-07-09 08:15:12,345] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 08:15:22,379] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 08:15:22] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-09 12:34:23,546] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 12:35:00,810] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-09 12:35:00,816] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 12:35:00] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 14:35:57,930] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 14:35:57,931] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 14:35:58,545] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 14:35:58,546] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 14:37:53,369] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 14:37:54,524] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 14:37:55,600] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 14:37:55,601] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 14:38:32,999] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 14:38:32] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 14:40:30,366] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 14:40:30,747] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 14:40:31,607] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 14:40:31,608] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 14:40:36,790] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 14:40:53,084] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 14:40:53] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 14:41:48,192] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 14:41:48,325] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 14:41:48,974] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 14:41:48,975] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 14:42:06,777] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 14:42:23,095] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 14:42:23] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 15:19:12,603] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:19:12,744] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:19:13,397] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:19:13,398] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:20:48,062] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:20:48,182] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:20:48,803] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:20:48,803] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:36:40,170] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:36:40,299] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:36:40,932] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:36:40,932] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:39:13,909] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:39:14,051] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:39:14,676] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:39:14,676] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:39:52,049] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:39:52,166] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:39:52,829] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:39:52,829] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:41:10,770] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:41:10,896] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:41:11,516] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:41:11,516] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:42:00,348] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:42:00,479] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:42:01,214] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:42:01,215] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:44:04,773] {sentenceproducer.py:34} Thread-2 ERROR in sentenceproducer: Exception while producing: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
Traceback (most recent call last):
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/kafkawrapper/sentenceproducer.py", line 30, in push_to_queue
    producer.send(topic, value=object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 564, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 691, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2020-07-09 15:44:04,779] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 15:44:04] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines_status HTTP/1.1[0m" 200 -
[2020-07-09 15:46:13,890] {sentenceservice.py:72} Thread-4 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 15:47:32,083] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 15:47:32,226] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:47:33,072] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:47:33,073] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:47:39,578] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 15:48:02,552] {sentenceservice.py:72} Thread-3 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 15:49:09,483] {sentenceproducer.py:34} Thread-2 ERROR in sentenceproducer: Exception while producing: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
Traceback (most recent call last):
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/kafkawrapper/sentenceproducer.py", line 30, in push_to_queue
    producer.send(topic, value=object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 564, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 691, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2020-07-09 15:49:09,484] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 15:49:09,494] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 15:49:09] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 15:49:25,345] {sentenceproducer.py:34} Thread-3 ERROR in sentenceproducer: Exception while producing: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
Traceback (most recent call last):
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/kafkawrapper/sentenceproducer.py", line 30, in push_to_queue
    producer.send(topic, value=object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 564, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 691, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2020-07-09 15:49:25,347] {sentenceservice.py:98} Thread-3 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 15:49:25,364] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 15:49:25] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 15:51:20,925] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 15:51:21,107] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 15:51:22,101] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 15:51:22,102] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 15:51:51,593] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 15:53:14,203] {sentenceproducer.py:34} Thread-2 ERROR in sentenceproducer: Exception while producing: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
Traceback (most recent call last):
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/kafkawrapper/sentenceproducer.py", line 30, in push_to_queue
    producer.send(topic, value=object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 564, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 691, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2020-07-09 15:53:14,205] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 15:53:14,216] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 15:53:14] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 16:00:21,401] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 16:00:21,584] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:00:22,676] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:00:22,677] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 16:00:29,897] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 16:00:30,053] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:00:32,533] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 16:00:32,534] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:00:33,145] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:00:33,146] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 16:00:44,532] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:02:07,357] {sentenceproducer.py:34} Thread-2 ERROR in sentenceproducer: Exception while producing: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
Traceback (most recent call last):
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/kafkawrapper/sentenceproducer.py", line 30, in push_to_queue
    producer.send(topic, value=object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 564, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/kafka/producer/kafka.py", line 691, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2020-07-09 16:02:07,359] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 16:02:07,373] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:02:07] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 16:03:35,799] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 16:03:35,926] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:03:37,066] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:03:37,066] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 16:05:46,597] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 16:05:46,734] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:06:47,467] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 16:06:47,468] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:06:48,169] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:06:48,170] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 16:06:52,051] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:07:14,940] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 16:07:14,952] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:07:14] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 16:10:04,153] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 16:10:04,281] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:10:04,921] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:10:04,922] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 16:10:20,284] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:10:36,529] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 16:10:36,541] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:10:36] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 16:18:39,663] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 16:18:39,664] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:18:40,178] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:18:40,179] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 628-366-080
[2020-07-09 16:18:59,766] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:19:16,024] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 16:19:16,032] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:19:16] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 16:20:48,443] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 16:20:48,562] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:20:49,227] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:20:49,228] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 628-366-080
[2020-07-09 16:21:35,467] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:21:51,662] {sentenceservice.py:98} Thread-2 INFO in sentenceservice: Sentences extracted Successfully! JOB ID: <usecase_code>-<13 digit epoch>
[2020-07-09 16:21:51,676] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:21:51] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-09 16:26:35,402] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py', reloading
[2020-07-09 16:26:35,507] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:26:36,164] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:26:36,165] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 628-366-080
[2020-07-09 16:26:42,462] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:26:58,752] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:26:58] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-09 16:27:25,735] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 16:27:25,847] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:27:26,464] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:27:26,465] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 628-366-080
[2020-07-09 16:27:29,615] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:27:45,843] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:27:45] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-09 16:28:13,020] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-09 16:28:13,124] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:28:13,730] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:28:13,730] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 628-366-080
[2020-07-09 16:28:29,039] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:28:51,715] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:28:51] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-09 16:31:05,304] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/python_env/rest/lib/python3.7/site-packages/requests/__init__.py', reloading
[2020-07-09 16:31:05,389] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:31:22,763] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 16:31:22,764] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:31:23,282] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:31:23,283] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 628-366-080
[2020-07-09 16:31:28,275] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:31:50,931] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:31:50] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-09 16:52:46,204] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-09 16:52:46,205] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-09 16:52:46,865] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-09 16:52:46,865] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-09 16:52:59,480] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-09 16:53:22,132] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [09/Jul/2020 16:53:22] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-10 15:07:37,923] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-10 15:07:38,049] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-10 15:07:38,685] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-10 15:07:38,686] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-10 15:34:27,081] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-10 15:34:27,226] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-10 15:34:27,859] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-10 15:34:27,860] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-10 15:56:27,426] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-10 15:56:27,426] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-10 15:56:27,999] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-10 15:56:28,000] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 120-574-164
[2020-07-10 15:57:05,163] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-10 15:57:56,468] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [10/Jul/2020 15:57:56] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-21 14:57:30,892] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 14:57:30,894] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-21 14:57:31,475] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-21 14:57:31,805] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 318-530-855
[2020-07-21 14:58:13,266] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 14:58:45,065] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 14:58:45] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 14:59:47,454] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py', reloading
[2020-07-21 14:59:47,574] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-21 14:59:48,196] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-21 14:59:48,196] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 318-530-855
[2020-07-21 14:59:52,594] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 14:59:52,595] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-21 14:59:53,166] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-21 14:59:53,166] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 318-530-855
[2020-07-21 15:00:00,043] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:02:25,308] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py', reloading
[2020-07-21 15:02:25,433] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-21 15:02:26,230] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-21 15:02:26,231] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 318-530-855
[2020-07-21 15:02:39,375] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:04:44,736] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/app.py', reloading
[2020-07-21 15:04:44,869] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-21 15:04:59,823] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:08:04,144] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2020-07-21 15:08:04,149] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:08:04] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 15:10:56,902] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:11:02,716] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:11:30,552] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 50, in wf_process
    result = self.process(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 87, in process
    output_dict  = pdf_html_with_vbs(path)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py", line 91, in pdf_html_with_vbs
    html_data =  add_width_and_line(html_data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 92, in add_width_and_line
    page_df = add_metadata(page_df)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 58, in add_metadata
    page_df['y'] = int(page_df['y'].astype(int))
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pandas/core/series.py", line 112, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
[2020-07-21 15:11:30,560] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:11:30] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 15:12:18,054] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:12:35,868] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:12:41,345] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:13:04,990] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 50, in wf_process
    result = self.process(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 87, in process
    output_dict  = pdf_html_with_vbs(path)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py", line 91, in pdf_html_with_vbs
    html_data =  add_width_and_line(html_data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 92, in add_width_and_line
    page_df = add_metadata(page_df)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 58, in add_metadata
    page_df['y'] = int(page_df['y'].values)
TypeError: only size-1 arrays can be converted to Python scalars
[2020-07-21 15:13:04,994] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:13:04] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 15:15:51,624] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:15:55,028] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:16:23,623] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 50, in wf_process
    result = self.process(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 87, in process
    output_dict  = pdf_html_with_vbs(path)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py", line 91, in pdf_html_with_vbs
    html_data =  add_width_and_line(html_data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 92, in add_width_and_line
    page_df = add_metadata(page_df)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 61, in add_metadata
    page_df['bottom'] =int( page_df['y'] + page_df['height'])
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pandas/core/series.py", line 112, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
[2020-07-21 15:16:23,629] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:16:23] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 15:16:58,529] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:17:02,359] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:17:26,559] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 50, in wf_process
    result = self.process(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 87, in process
    output_dict  = pdf_html_with_vbs(path)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py", line 91, in pdf_html_with_vbs
    html_data =  add_width_and_line(html_data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 92, in add_width_and_line
    page_df = add_metadata(page_df)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/ptf_to_html_integration.py", line 63, in add_metadata
    page_df['right'] = int(page_df['x'] + page_df['width'])
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pandas/core/series.py", line 112, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
[2020-07-21 15:17:26,564] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:17:26] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 15:17:46,371] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:17:51,750] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:18:32,406] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2020-07-21 15:18:32,408] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:18:32] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-21 15:24:01,720] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-21 15:24:05,996] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:24:41,479] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:24:41] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-21 15:24:54,198] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-21 15:28:01,317] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [21/Jul/2020 15:28:01] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-22 10:24:30,216] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-22 10:27:29,262] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-22 10:28:47,657] {app.py:1892} Thread-1 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 50, in wf_process
    result = self.process(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 87, in process
    output_dict  = pdf_html_with_vbs(path)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py", line 95, in pdf_html_with_vbs
    ocr_data = post_request(ocr_api,param)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/utilities/visual_translater.py", line 15, in post_request
    return r.json()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-07-22 10:28:47,674] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [22/Jul/2020 10:28:47] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-22 10:40:34,695] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-22 10:40:34,696] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2020-07-22 10:40:35,277] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2020-07-22 10:40:35,606] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 685-814-846
[2020-07-22 10:40:58,211] {sentenceservice.py:72} Thread-2 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-22 10:41:30,732] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [22/Jul/2020 10:41:30] "[35m[1mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
[2020-07-22 10:43:57,661] {sentenceservice.py:72} Thread-3 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-22 10:44:39,103] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [22/Jul/2020 10:44:39] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-22 10:48:07,136] {sentenceservice.py:72} Thread-4 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-22 10:49:10,274] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [22/Jul/2020 10:49:10] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
[2020-07-23 10:52:10,120] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-23 10:52:49,660] {sentenceservice.py:72} Thread-1 INFO in sentenceservice: Alignment process starts for job: <usecase_code>-<13 digit epoch>
[2020-07-23 10:53:22,211] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [23/Jul/2020 10:53:22] "[37mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 200 -
